use_frameworks!

target 'podThreeTest_Example' do
  pod 'podThreeTest', :path => '../'

  target 'podThreeTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
